env:
  global:
    - CC_TEST_REPORTER_ID: ecb24ed0e4ed09f50a512e0b9490e0caa3e2409bb5f1220af8935514279293d9
    - GIT_COMMITTED_AT=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git log -1 --pretty=format:%ct; else git log -1 --skip 1 --pretty=format:%ct; fi)
language: swift
xcode_workspace: ios-base.xcworkspace
xcode_scheme: ios-base-develop
osx_image: xcode10.2
cache:
  - bundler
  - cocoapods
before_install:
  - pod repo update
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-darwin-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
install:
  - bundle install
  - pod install
script:
  - set -o pipefail
  - xcodebuild -workspace ios-base.xcworkspace -scheme ios-base-develop -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.4' build test | xcpretty --test --color
after_script:
  - slather coverage
  - ./cc-test-reporter after-build -t cobertura --exit-code $TRAVIS_TEST_RESULT
